export enum Role {
  STUDENT = 'STUDENT',
  CR = 'CR',
  DEVELOPER = 'DEVELOPER',
}

export enum StudentType {
  HOSTELLER = 'HOSTELLER',
  DAY_SCHOLAR = 'DAY_SCHOLAR',
}

export enum RoomStatus {
  FREE_BY_TIMETABLE = 'FREE_BY_TIMETABLE',
  OCCUPIED_BY_TIMETABLE = 'OCCUPIED_BY_TIMETABLE',
  REPORTED_FREE = 'REPORTED_FREE',
  UNKNOWN_STALE = 'UNKNOWN_STALE',
  MAINTENANCE = 'MAINTENANCE',
}

export enum AttendanceState {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  NOT_UPDATED = 'NOT_UPDATED',
  UNKNOWN = 'UNKNOWN',
  REQUESTED = 'REQUESTED',
}

export enum SubmissionType {
  ASSIGNMENT = 'ASSIGNMENT',
  LAB_RECORD = 'LAB_RECORD',
  PRACTICAL_FILE = 'PRACTICAL_FILE',
  PROJECT = 'PROJECT',
  VIVA_FILE = 'VIVA_FILE',
  PRINTED_FORM = 'PRINTED_FORM',
  DOCUMENT = 'DOCUMENT',
  OTHER = 'OTHER',
}

export enum SubmissionStatus {
  NOT_SUBMITTED = 'NOT_SUBMITTED',
  SUBMITTED = 'SUBMITTED',
  SUBMITTED_DIGITALLY = 'SUBMITTED_DIGITALLY',
  SUBMITTED_PHYSICALLY = 'SUBMITTED_PHYSICALLY',
  COLLECTED = 'COLLECTED',
  WITH_FACULTY = 'WITH_FACULTY',
  RETURNED = 'RETURNED',
  REJECTED_CORRECTION_REQUIRED = 'REJECTED_CORRECTION_REQUIRED',
  UNKNOWN = 'UNKNOWN',
}

export enum ReminderCategory {
  EXAM = 'EXAM',
  VIVA = 'VIVA',
  ASSIGNMENT = 'ASSIGNMENT',
  LAB = 'LAB',
  PROJECT = 'PROJECT',
  FEE = 'FEE',
  EVENT = 'EVENT',
  REGISTRATION = 'REGISTRATION',
  SCHOLARSHIP = 'SCHOLARSHIP',
  DOCUMENT = 'DOCUMENT',
  ATTENDANCE = 'ATTENDANCE',
  OTHER = 'OTHER',
}

export enum Priority {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  IMPORTANT = 'IMPORTANT',
  URGENT = 'URGENT',
}

export enum ReminderSchedule {
  ONE_DAY = 'ONE_DAY',
  TWELVE_HOURS = 'TWELVE_HOURS',
  THREE_HOURS = 'THREE_HOURS',
  ONE_HOUR = 'ONE_HOUR',
  CUSTOM = 'CUSTOM',
}

export enum TargetAudience {
  COLLEGE = 'COLLEGE',
  DEPARTMENT = 'DEPARTMENT',
  SEMESTER = 'SEMESTER',
  SECTION = 'SECTION',
  INDIVIDUAL = 'INDIVIDUAL',
}

